### ISSUE TITLE
Problemas para Configurar - No valid credentials

### ISSUE THREAD

**Issue by crishonsou** [P0ssuidao/terraguard#1]
Bom dia! Tudo bem? Espero que sim.

Estou com um problema para fazer funcionar. Rodo o terraform em container, possuo um arquivo .env com as minhas credenciais e também as tenho configurado no diretorio default (~/.aws). Entretanto, continuo tomando o mesmo erro de que não há configuração de credenciais válidas:

## Alterações no main.tf

terraform {
  required_providers {
    aws = {
      source = "hashicorp/aws"
      version = "3.50.0"
    }
  }
}

provider "aws" {
  region                  = var.region
  shared_credentials_file = "<redacted>/<redacted>/.aws/credentials"
  profile                 = "<redacted>"
}

## Terraform init

$ sudo make terraform-init
docker run --rm -v $PWD:/app -v $HOME/.ssh/:/root/.ssh/ -w /app/ -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e \
AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY hashicorp/terraform:latest init -upgrade=true
Upgrading modules...
- ec2 in modules/ec2
- key in modules/key
- sg in modules/sg

Initializing the backend...

Initializing provider plugins...
- Finding latest version of hashicorp/local...
- Finding latest version of hashicorp/time...
- Finding latest version of hashicorp/null...
- Finding latest version of hashicorp/tls...
- Finding hashicorp/aws versions matching "3.50.0"...
- Using previously-installed hashicorp/time v0.7.2
- Using previously-installed hashicorp/null v3.1.0
- Using previously-installed hashicorp/tls v3.1.0
- Using previously-installed hashicorp/aws v3.50.0
- Using previously-installed hashicorp/local v2.1.0

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

## Terraform validate

$ sudo make terraform-validate
docker run --rm -v $PWD:/app -v $HOME/.ssh/:/root/.ssh/ -w /app/ -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e \
AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY hashicorp/terraform:latest validate
Success! The configuration is valid.

## Terraform plan

$ sudo make terraform-plan    
docker run --rm -v $PWD:/app -v $HOME/.ssh/:/root/.ssh/ -w /app/ -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e \
AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY hashicorp/terraform:latest plan -out=tfplan
╷
│ Error: error configuring Terraform AWS Provider: no valid credential sources for Terraform AWS Provider found.
│ 
│ Please see https://registry.terraform.io/providers/hashicorp/aws
│ for more information about providing credentials.
│ 
│ Error: NoCredentialProviders: no valid providers in chain. Deprecated.
│       For verbose messaging see aws.Config.CredentialsChainVerboseErrors
│ 
│ 
│   with provider["registry.terraform.io/hashicorp/aws"],
│   on main.tf line 10, in provider "aws":
│   10: provider "aws" {
│ 
╵

## Teste de acesso a aws usando as mesmas credenciais/profile configurados no .env

$ aws s3 ls --profile <redacted> --region sa-east-1
2021-06-10 15:38:44 cf-templates-heobifcgwdf0-us-east-1

**Comment by gchamon** [comment]
```
shared_credentials_file = "//.aws/credentials"
```
Não parece ta muito certo. De acordo com https://registry.terraform.io/providers/hashicorp/aws/latest/docs#shared-credentials-file :
```
provider "aws" {
  region                  = "us-west-2"
  shared_credentials_file = "/Users/tf_user/.aws/creds"
  profile                 = "customprofile"
}
```

Verifica o caminho do shared_credentials_file.

**Comment by crishonsou** [comment]
Efetuei algumas alterações em meu Makefile (que executa os comandos do terraform em docker) e funcionou normalmente.
