### ISSUE TITLE
GCP More than 30 minutes - Still creating...

### ISSUE THREAD

**Issue by sniffski** [P0ssuidao/terraguard#10]
null_resource.ansible: Still creating... [23m51s elapsed]
null_resource.ansible: Still creating... [28m4s elapsed]
null_resource.ansible: Still creating... [29m20s elapsed]
null_resource.ansible: Still creating... [29m30s elapsed]
null_resource.ansible: Still creating... [29m40s elapsed]
null_resource.ansible: Still creating... [29m50s elapsed]
null_resource.ansible: Still creating... [30m0s elapsed]
null_resource.ansible: Still creating... [30m10s elapsed]
null_resource.ansible: Still creating... [30m20s elapsed]
null_resource.ansible: Still creating... [30m30s elapsed]
null_resource.ansible: Still creating... [30m40s elapsed]

**Comment by R3DRUN3** [comment]
> null_resource.ansible: Still creating... [23m51s elapsed] null_resource.ansible: Still creating... [28m4s elapsed] null_resource.ansible: Still creating... [29m20s elapsed] null_resource.ansible: Still creating... [29m30s elapsed] null_resource.ansible: Still creating... [29m40s elapsed] null_resource.ansible: Still creating... [29m50s elapsed] null_resource.ansible: Still creating... [30m0s elapsed] null_resource.ansible: Still creating... [30m10s elapsed] null_resource.ansible: Still creating... [30m20s elapsed] null_resource.ansible: Still creating... [30m30s elapsed] null_resource.ansible: Still creating... [30m40s elapsed]

Same thing happen with AWS.

**Comment by P0ssuidao** [comment]
Fixed !
Could you try again please @sniffski @R3DRUN3 ?
