### ISSUE TITLE
Ansible error when -var "mobile=false" 

### ISSUE THREAD

**Issue by diegonicacio** [P0ssuidao/terraguard#7]
OS: Linux archlinux 5.13.7-arch1-1 #1 SMP PREEMPT Sat, 31 Jul 2021 13:18:52 +0000 x86_64 GNU/Linux
Terraform: v1.0.3
Ansible: 2.11.3
Python: 3.9.6
Jinja: 3.0.1

Command:
```bash
sudo terraform apply -var "do_token=[REDACTED]"
```

Output:
```bash
TASK [client_install : Add Keys to a host holder] ****************************** fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'stdout'\n\nThe error appears to be in '/home/dnc/repos/terraguard/ansible/roles/client_install/tasks/main.yaml': line 51, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: \"Add Keys to a host holder\"\n  ^ here\n"}
```

Issue happens on DigitalOcean, Azure and AWS. (Didn´t test GCP yet, but probably as well)

**Comment by P0ssuidao** [comment]
I fixed adding a conditional and change a var mobile in terraform.

Can you try again ?

**Comment by diegonicacio** [comment]
Can confirm the below commits fixed the issue.

da9a27dcf6b9099e010df27d7079e3dfd62bf25f
c4e756f5f91813dad8ed60269abe61d0d72a5a1b
d58a3eed1dd2d3e969988804fdadfcfd9b544bdf
e8a08a2b38069eb9ad8ffe7ee1d6fbf409a671f7

Thanks
